
# Estructuras de Datos Numpy 🙂

 
Cuando realmente queremos hacer cálculos con listas de números, debemos usar los arrays. El módulo numpy nos da acceso a los arrays y a una enorme cantidad de métodos y funciones aplicables a los mismos. Naturalmente, numpy incluye funciones matemáticas básicas similares al módulo math, las completa con otras más elaboradas y además incluye algunas utilidades de números aleatorios, ajuste lineal de funciones y muchas otras.

## 📙📗📔Bibliotecas

Para trabajar con numpy y los arrays, importamos el módulos de alguna manera:

In [2]:
%pylab inline
import numpy              # Cargar el modulo numpy, o bien
import numpy as np        # cargar el modulo numpy, llamándolo np, o bien
from numpy import array   #cargar la función de array
from numpy import *       # cargar todas funciones de numpy


Populating the interactive namespace from numpy and matplotlib


Si cargamos el módulo solamente, accederemos a las funciones como numpy.array() o np.array(), según cómo importemos el módulo; si en lugar de eso importamos todas las funciones, accederemos a ellas directamente (e.g. array()). Por comodidad usaremos por ahora esta última opción, aunque muy a menudo veremos que usa la notación np.array(), especialmente cuando trabajamos con varios módulos distintos.

## Un array se puede crear explícitamente o a partir de una lista de la forma siguiente:

In [3]:
x = array([2.0, 4.6, 9.3, 1.2])      # Creacion de un array directamente
notas = [ 9.8, 7.8, 9.9, 8.4, 6.7]  # Crear un lista
notas = array(notas)                # y convertir la lista a array

In [5]:
x

array([2. , 4.6, 9.3, 1.2])

In [6]:
notas

array([9.8, 7.8, 9.9, 8.4, 6.7])

In [7]:
type(x)

numpy.ndarray

In [8]:
type(notas)

numpy.ndarray

Existen métodos para crear arrays automáticamente:

In [9]:
numeros = arange(10.)       # Array de numeros(floats) de 0 a 9
print(numeros)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [10]:
lista_ceros = zeros(10)             # Array de 10 ceros (floats)
print(lista_ceros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [11]:
lista_unos = ones(10)               # Array de 10 unos (floats)
print(lista_unos)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [12]:
otra_lista = linspace(0,30,8)       # Array de 8 números, de 0 a 30 ambos incluidos
print(otra_lista)

[ 0.          4.28571429  8.57142857 12.85714286 17.14285714 21.42857143
 25.71428571 30.        ]


Los arrays se indexan prácticamente igual que las listas y las cadenas de texto; aquí hay algunos ejemplos:

In [13]:
print(numeros[3:8])           # Elementos desde el tercero al septimo

[3. 4. 5. 6. 7.]


In [14]:
print(numeros[:4])            # Elementos desde el primero al cuarto

[0. 1. 2. 3.]


In [15]:
print(numeros[5:])            # Elementos desde el quinto al final

[5. 6. 7. 8. 9.]


In [16]:
print(numeros[-3])            # El antepenúltimo elemento (devuelve un elemento, no un array)

7.0


In [17]:
print(numeros[:])             # Todo el array, equivalente a print(numeros)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [18]:
print(numeros[2:8:2])        # Elementos del segundo al septimo, pero saltando de dos en dos

[2. 4. 6.]


Al igual que las listas, podemos ver el tamaño de un array unidimensional con len(), aunque la manera correcta de conocer la forma de un array es usando el método shape():

In [19]:
print(len(numeros))
print(numeros.shape)


10
(10,)


Nótese que el resultado del método shape() es una tupla, en este caso con un solo elemento ya que el array números es unidimensional.

# NDARRAY

Formación multidimensional homogenea, todos los elementos son del mismo tipo



## Creación de un ndarray de una dimensión

Desde una lista de python

In [3]:
a = array([1,2,3,4])

In [4]:
a

array([1, 2, 3, 4])

In [5]:
type(a)

numpy.ndarray

Desde una tupla de python


In [5]:
b = array((1.1,2.2,3.3,4))

In [6]:
b

array([ 1.1,  2.2,  3.3,  4. ])

In [7]:
type(b)

numpy.ndarray

## Creación de un narray de 2 dimensiones


In [10]:
a2= array([[1,2,3],[4,5,6]])

In [11]:
a2


array([[1, 2, 3],
       [4, 5, 6]])

### Atributos más importantes

ndarray.ndim => numero de dimensiones(también llamado rank)

In [12]:
a2.ndim

2

ndarray.shape => tupla que indica las dimensiones de la formación.

El tamaño de la formación en cada dimensión (n,m)=> n lineas y m columnas

In [13]:
a2.shape

(2, 3)

ndarray.size => número total de elementos en la formación

In [14]:
a2.size

6

ndarray.dtype => tipo de elementos en la formación

In [15]:
a2.dtype

dtype('int32')



## Creación de formaciones de n-dimensiones😄

De la misma forma que se transforma listas de listas en formaciones de 2 dimensiones, se puede transformar listas de listas en ndimensiones y asi sucesivamente

In [16]:
a3 = array([[[[1, 2], [3, 4]], [[5, 6], [7, 8]]],[[[9, 10], [11, 12]], [[13, 14], [15,16]]]])

In [17]:
a3

array([[[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]]],


       [[[ 9, 10],
         [11, 12]],

        [[13, 14],
         [15, 16]]]])

In [18]:
a3.size

16

In [19]:
a3.ndim

4

In [20]:
a3.shape

(2, 2, 2, 2)


## Generación Automática de Elementos

Formación rellena con ceros zeros(tupla con dimensiones) => creará una formación con las dimensiones introducidas en su argumento (una tupla)


In [22]:
z= zeros((4,5))

In [23]:
z

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

Formación rellena con unos ones(tupla con dimensiones) => creará una formación con unos


In [24]:
o = ones((4,5))

In [25]:
o

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

Formación rellena con elementos vacíos empty(tupla con dimensiones) => creará una formación con elementos vacíos

In [27]:
e = empty((2,3))

In [28]:
e

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

Formación rellena secuencialmente arange(de, a, incremento) => crea una formación de una dimensión con una secuencia de números


In [32]:
s = arange(5,10,1)

In [33]:
s

array([5, 6, 7, 8, 9])

linspace(de, a, número de elementos) => misma funcionalidad pero indicando el número de elementos en lugar del incremento. Más adecuada para tratar con números decimales


In [34]:
s2 = linspace(5.5, 10, 20)


In [35]:
s2

array([  5.5       ,   5.73684211,   5.97368421,   6.21052632,
         6.44736842,   6.68421053,   6.92105263,   7.15789474,
         7.39473684,   7.63157895,   7.86842105,   8.10526316,
         8.34210526,   8.57894737,   8.81578947,   9.05263158,
         9.28947368,   9.52631579,   9.76315789,  10.        ])

Formación rellena aleatoriamente random.random(tupla con dimensiones) => crea una formación con las dimensiones introducidas y la rellena con números aleatorios de la distribución [0, 1)


In [36]:
 r = random.random( (2, 3) )


In [37]:
r

array([[ 0.02831921,  0.79795985,  0.25353923],
       [ 0.58552862,  0.32999149,  0.7537629 ]])