## 💜Funciones y Objetos en Python

In [ ]:
# Solucuion a desafios anteriores

In [1]:
def simple_primo(x):
    for i in range(2,x):
        if x%i == 0:
            print('No es primo')
            break
    else:
        print("Primo")

In [7]:
simple_primo(14)

No es primo


In [3]:
def simple_mcd(x,y):
    # Solo dividir hasta el menor numero
    minor = min(x,y)
    cds = [] # divisores
    for i in range(1,minor+1):
        if x%i == 0 and y%i ==0:
            cds.append(i)
    print(cds)
    return cds[-1]
    

In [4]:
mcd = simple_mcd(12,36)
print(mcd)

[1, 2, 3, 4, 6, 12]
12


## Listas parte 2

Antes de comenzar con las funciones vamos a repasar las listas. Ya que las vimos brevemente.

Existen 2 maneras de recorrer una lista

In [5]:
lista = ['a', 3, 4.5, 'b', 7] # las listas pueden tener distintos tipos de datos en su interior!

for i in lista:
    print(i)

a
3
4.5
b
7


De la anterior manera i toma el valor de cada variable en la lista. Pero debes saber que interamente las listas tienen **índices**. Esto es cada valor tiene una posición en la lista y puedes uar esta posicion para acceder al valor. Los indices comienzan en 0 (primera posición) y van aumentando.

> lista[i] siendo i un entero, es una forma de acceder al valor en la posicion i en la lista

- lista[0] es una cadena
- lista[1] es un numero entero int
- lista[2] es un float o numero decimal

Ahora usaremos la funcion len() para obtener la longitud de la lista y la funcion range() para generar indices. Observa este código:

In [6]:
for i in range(len(lista)):
    print("Indice: ", i, "valor: ", lista[i])

Indice:  0 valor:  a
Indice:  1 valor:  3
Indice:  2 valor:  4.5
Indice:  3 valor:  b
Indice:  4 valor:  7


Podemos usar la funcion range para cambiar el orden o los saltos en la iteracion

In [7]:
for i in range(0, len(lista),2): # usando range (inicio, final, salto)
    print("Indice: ", i, "valor: ", lista[i])

Indice:  0 valor:  a
Indice:  2 valor:  4.5
Indice:  4 valor:  7


In [8]:
for i in range(len(lista)-1,0,-1): # usando range (final, comienzo, salto)
    print("Indice: ", i, "valor: ", lista[i])

Indice:  4 valor:  7
Indice:  3 valor:  b
Indice:  2 valor:  4.5
Indice:  1 valor:  3


> Por qué uso la longitud -1 ?

### List comprehension

Hay maneras de hacer listas con lógica en python. Además esto es muy rápido ya que internamente es un *generador* (ya lo veremos más adelante) 

In [22]:
# Quiero los numeros en la lista 
enteros_lista = [i for i in lista if type(i) == int]
print(enteros_lista)

[3, 7]


# Funciones

Hasta ahora haz utilizado funciones quizás sin darte cuenta. 

- print()
- len()
- range()
- type()
- int()

Pero... ¿ cómo definirías una función?

Una funcion es una pieza de código que recibe unos parámetros (entradas) y ejecuta un proceso que puede o no retornar un resultado.



```python

def nombre_funcion(parametros):
    .... operaciones sobre los parametros
    
```

Por qué crear funciones?

- Podemos reusar código encapsulandolo en una funcion para usarlo con diferentes parámetros!

In [23]:
def cuadrado(x):
    x2 = x*x
    return x2

print(cuadrado(2))
print(cuadrado(9))

4
81


In [9]:
# definiendo una funcion
def saluda(mi_nombre, mi_edad):
    print("Hola mi nombre es {nombre} y tengo {edad}.".format(nombre=mi_nombre, edad=mi_edad))

In [10]:
# llamando a la funcion! Si no la llamas no se ejecuta
saluda('Wanda', 26)    

Hola mi nombre es Wanda y tengo 26.


# Ejercicio

Crea una funcion que tome el valor de la comida y la propina que el usuario quiere dar. Haz que imprima un mensaje "No seas tacaño" si esta es menor del 10% de lo consumido.

In [12]:
def calcula_porcentaje_propina(valor_comida, propina):
    min_prop = None
    if None:
        print('No seas tacaño!')
    pass # reemplaza esto por tus calculos

Las funciones pueden retornar valores o solo realizar acciones como la funcion saluda.

## Recursividad

Una función recursiva es aquella que se llama a sí misma.

<img src='Notebooks_imagenes/poo.jpg'/>

Y para ilustrar haremos una funcion calcule el factorial de un numero.

El factorial de un numero n se escribe como $n!$

$$n! = 1 * 2 * 3 *... (n-1) * n$$

**Ejemplos **

$3! = 1*2*3 = 6$ 

$5! = 1*2*3*4*5 = 120$

Podriamos calcularlo con un for pero... sabemos de una propiedad matemática

$$n! = (n-1)!* n$$

In [26]:
def factorial(n):
    if n == 1:
        return 1
    else:
        return n * factorial(n-1)
    
factorial(6)

720

## Funciones lambda

Las funciones lambda son funciones anónimas. No tienen nombre.

Son utiles para hacer un proceso que no va ser utilizado por otras partes del código. Es unaexpresion compacta. La sintaxis es de la siquiente manera:

```python
lambda argumentos : expresion
```

In [27]:
x = lambda a : a + 10

print(x(4))

14


# Programación Orientada a objetos

En python todo es un objeto, indirectamente has venido usando los objetos. Este estilo de programación lleva todo a un nivel más alto de abstracción que aunque al comienzo puede pareer más  complicado en realidad facilita las cosas para los programadores a la hora de hacer buen software. A continuacion algunos de los conceptos clave en POO:

#### Clase

Es un prototipo de objeto definido a partir de un conjunto de **atributos** que caracterizan cualquier objeto de la clase. También se definen en la clase el conjunto de métodos o **funciones** propios del objeto.

#### Variable de Clase 

Una variable que es compartida por todas las intsancias de la clase, se define dentro de la clase.

#### Instancia

Es un objeto individual de cierta clase.

#### "Instanciar"

La creación de una instancia de una clase.

#### Variable de instancia

Una variable que es definida dentro de un método y que pertenece sólo a la instancia actual de esa clase.f a class.

#### Método

Es una función que es definida dentro de una clase.

#### Objeto 

Una instancia de estructur de datos definida por su clase. Tiene variables de clase y variables de instancia en sus métodos.

####  Sobrecarga de operadores

Asignar una o más funciones a un operaor particular. Por ejemplo debes notar que el operador "+" tiene comportamiento diferente con cadenas y números! 

#### Init()

Es un método especial, llamado **constructor** que sirve para inicializar o crear una instancia de una clase. Toma como argumento a sí mismo **self**. Contrario a *init*, tambien existe un método **destructor** *del()*.

### Ejemplo (mental)

Un ejemplo para llevar todas estas definiciones a una representación común es imaginar que creas una clase *Gato.* Defines atributos como numero de colores, peso, edad, color de ojos, si es de pelo largo o corto... en fin. También como gato tiene métodos como: comer(), dormir(), ronronear(), jugar()

Ahora imagina que instanciamos un objeto llamado pusheen, pusheen pertenece a la clase Gato y como tal puede hacer todos los métodos. 

![SegmentLocal](Notebooks_imagenes/gatitos.gif "segment")

> Atributos son propiedades del objeto. Métodos son funciones que se pueden hacer sobre el objeto que permiten modificar , iniciar o destruir.

In [28]:
class Cat:
    'Base comun para todos los gatos'
    catCount = 0 #class variable
    def __init__(self, name, color, caracter):
        self.name = name
        self.color = color
        self.caracter = caracter
        Cat.catCount += 1
        
    def __del__(self):
        class_name = self.__class__.__name__
        print(class_name, "destroyed </3 ")
        Cat.catCount += 1

    def displayCount(self):
        print("Total cats %d" % Cat.catCount)
        
    def displayCat(self):
        print("My name is ", self.name,  ", My fur is ", self.color ," and I'm a ",self.caracter, "kitty :3")
    
    def meow(self):
        print ('Miau, gimme food >:3 ')
    


In [29]:
gato1 = Cat(name='pusheen', color='gray', caracter='playful')
print(gato1)

In [30]:
Cat.catCount # variable de clase! :D 

1

In [31]:
gato1.displayCat()

My name is  pusheen , My fur is  gray  and I'm a  playful kitty :3


In [32]:
gato1.meow()

Miau, gimme food >:3 


In [33]:
print( getattr(gato1,'name'))

pusheen


In [34]:
del(gato1)

Cat destroyed </3 


## Herencia

La herencia es un cocepto por el cual puedes crear una clase que hereda de una más sencilla y luego añadirle más funcionalidades. Por ejemplo: 

```python
class Dog:
    species = 'mammal'

class SomeBreed(Dog):
    breed = 'bulldog'


frank = SomeBreed()
print(frank.species, frank.breed)
```

# Ejercicio

- Crea una nueva instancia llamada gata3. Dale atributos de tu gusto.
- La  programación es creativa, que otros métodos puedes añadir a la clase Cat?
- Crea una clase que herede de la clase Gato, similar al ejemplo anterior

In [ ]:
# crea un nuevo gato

# Librerias

Las librerías o módulos son código creado por otras personas que podemos usar para no tener que "reinventar la rueda". Pueden traer variables y funciones útiles optimizadas. La comunidad de Python en el mundo es muy grande y es casi seguro que al empezar un proyecto, si buscas antecedentes encontrarás una librería con lo que buscas o algo muy parecido.

Para importar una libreria existen varias formas:

```python
# importando todo el modulo
import math  
a = 2
root = math.sqrt(a)

# importando todo con notacion *
from math import *
root = sqrt(a)

## importando solo algunas funciones del modulo
from math import sqrt
root = sqrt(a)

```

- Math es una librería básica de Python con funciones matemáticas, la primera forma importa de math TODAS las funciones. 
- La segunda también y ademas te puede crear conflictos. Que tal si tienes en tu codigo una funcion sqrt?
- La tercera es mejor práctica y es importar solo lo que necesitamos.

# Ejercicios

- 1) Crea una función que tome una lista de nombres como entrada y retorne solo aquellos que terminen en 'a'. **Pista: ** las cadenas son como lista puedes obtener el último caracter con nombre[-1].
- 2) Haz lo mismo que en el numeral 1) una usando list comprehension.
- 3) Crea una clase llamada Poligono. Que tenga el numero de lados y longitud de estos como atributo. Crea una  funcion que sume los lados del polígono (perímetro)


# Usando Numpy

La librería numpy nos sirve para crear arreglos y hacer operaciones sobre estos. Vas a ver que hay operaciones vectorizadas que nos hace la sintaxis más limpia y el código mas rápido.

## Vectores

In [14]:
import numpy as np 

vector_a = np.array([1,4,8])
vector_a

array([1, 4, 8])

In [15]:
vector_a.shape # es un vector fila

(3,)

In [17]:
vector_b = np.array([[1],[3],[9]])
vector_b

array([[1],
       [3],
       [9]])

In [19]:
vector_b.shape # vector columna

(3, 1)

## Matrices

similar la sintaxis...

In [20]:
matriz_ejemplo = np.array([[7,5],[6,3],[0,2]])
matriz_ejemplo

array([[7, 5],
       [6, 3],
       [0, 2]])

In [22]:
matriz_ejemplo.shape

(3, 2)

> Normalmente para multiplicar una matriz por un número habria que recorrer el arreglo con dos for  (uno para filas y otro para columnas) pero con numpy hacer esto es muy sencillo.

In [23]:
matriz_ejemplo2 = 2*matriz_ejemplo
matriz_ejemplo2

array([[14, 10],
       [12,  6],
       [ 0,  4]])

Podemos multiplicar dos matrices elemento a elemento simplemente deben tener la misma dimension!

In [25]:
matriz_ejemplo*matriz_ejemplo2

array([[98, 50],
       [72, 18],
       [ 0,  8]])

Y multiplicar matrices, siempre que cumplan la condicion (m,n), (n,x)

In [26]:
np.matmul(matriz_ejemplo, matriz_ejemplo2)

ValueError: shapes (3,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

sacar traspuestas es simple!

In [27]:
matriz_ejemplo.T

array([[7, 6, 0],
       [5, 3, 2]])

In [28]:
np.matmul(matriz_ejemplo, matriz_ejemplo2.T)

array([[148, 114,  20],
       [114,  90,  12],
       [ 20,  12,   8]])

Crear  arreglos de ceros o unos 

In [29]:
ceros = np.zeros((2,3))
ceros

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [31]:
unos = np.ones((4,5))
unos

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [32]:
# matriz identidad
id3 = np.eye(N=3, M=3)
id3

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [44]:
Z = np.random.random((3,3))
Z

array([[ 0.23928386,  0.60093895,  0.65802148],
       [ 0.13288357,  0.77372552,  0.72407913],
       [ 0.21061873,  0.98914382,  0.86597271]])

In [48]:
Z.max(), Z.min(), Z.mean(), Z.std()

(0.98914381949160102,
 0.13288357360200764,
 0.57718530887703223,
 0.29180758967496645)

Podemos hacer "slicing" de estos arrays, como en las listas

In [39]:
Z[:,0]

array([ 0.4657765 ,  0.69382243,  0.1743956 ])

In [40]:
Z[1,:]

array([ 0.69382243,  0.45250222,  0.25619407])

In [52]:
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# Ejercicio 



- Crea una matriz de numeros aleatorios.
- Normalizala, esto es los numeros deben estar entre 0 y 1.

Z = (Z - Zmin)/(Zmax - Zmin)

Funcion para generar matriz xon numeros entre a,b aleatorios : np.random.random((m,n))

http://www.numpy.org/