<a href="https://colab.research.google.com/github/marisbotero/DataScienceFEM/blob/master/Holi_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
lista = ['a', 3, 4.5, 'b', 7]
enteros_lista = [i for i in lista if type(i) == int]
print(enteros_lista)

[3, 7]


In [0]:

import numpy as np 

vector_a = np.array([1,4,8])
vector_a

array([1, 4, 8])

# ¿Qué es Numpy?#

es una biblioteca de álgebra lineal para Python que tiene enlaces a bibliotecas C, estructuras de datos y funcionalidades que la hace increíblemente rápida y eficiente para procesar arreglos y matices.

#¿ Por qué usar numpy?#

Es una forma útil de resolver algunos problemas que pueden ser demandantes al usar arreglos e iteraciones regulares

#¿ cómo obtener numpy?#

**La forma fácil**

Si se tiene python y pip, se puede instalar mediante este sistema, solamente es abrir un terminal y digitar:

```
pip install numpy
```

#¿Cómo usar numpy#
Luego de instalarlo (o de crear un cuaderno), el primer paso para utilizar numpy es importar el paquete.

In [0]:
import numpy as np

##Acceso a  los elementos del arreglo##

Para acceder a los elementos de un arreglo o matriz en numpy se utiliza la misma notación que en los arreglos regulares de Python (incluyendo las subdivisiones)

In [0]:
my_array = np.random.randint(0, 100, 10) # crea un arreglo de 10 enteros entre 0 y 99 
# Devuelve enteros aleatorios de bajo (inclusivo) a alto (exclusivo).

print("arreglo original\n", my_array)

print("el quinto elemento\n", my_array[4] )

print("antes del quinto elemento\n", my_array[:4])

print("despues del quinto elemento\n", my_array[4:])

print("elementos intermedios\n", my_array[2:7])

print("último elemento", my_array[-1])

print("elementos en posiciones impares", my_array[1::2])

print("arreglo invertido", my_array[::-1])


arreglo original
 [75 36 56 85 47 96 68 51  0 58]
el quinto elemento
 47
antes del quinto elemento
 [75 36 56 85]
despues del quinto elemento
 [47 96 68 51  0 58]
elementos intermedios
 [56 85 47 96 68]
último elemento 58
elementos en posiciones impares [36 85 96 51 58]
arreglo invertido [58  0 51 68 96 47 85 56 36 75]


In [0]:
# Array de 3 filas y tres columnas, creado implícitamente
arr0 = np.array([[10,20,30],[9, 99, 999],[0, 2, 3]])
print(arr0)


[[ 10  20  30]
 [  9  99 999]
 [  0   2   3]]


In [0]:
# Array de ceros con 2 filas y 3 columnas
arr1 = np.zeros((2,3))
print(arr1)


[[0. 0. 0.]
 [0. 0. 0.]]


In [0]:
# Array unidimensional de 9 elementos y cambio su forma a 3x3
arr3 = np.arange(9).reshape((3, 3))
print(arr3)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [0]:
#creación de una matriz de 6 filas y 5 columnas en numpy con numeros aleatorios entre 0 y 99
array6x5= np.random.randint(0,100,size=(6,5))
print("matriz de 6 filas y 5 columnas\n", array6x5)

matriz de 6 filas y 5 columnas
 [[ 6 72 66  9  0]
 [54 37 27 41 35]
 [27 79 52 38 68]
 [48 77 64 94 52]
 [26 98 43 20 38]
 [31 42 98 61 84]]


El método reshape()  permite reorganizar la matriz de acuerdo a cómo se necesite

In [0]:
array5x6 = array6x5.reshape(5,6)
print("matriz de 5 filas y 6 columnas\n", array5x6)

array3x10 = array6x5.reshape(3,10)
print("matriz de 3 filas y 10 columnas\n", array3x10)

#si solamente se conoce una dimensión se puede pasar un parámetro para que numpy lo asuma
array_x15 = array6x5.reshape(15,-1)
print("matriz de ? filas y 15 columnas\n", array_x15)



matriz de 5 filas y 6 columnas
 [[ 6 72 66  9  0 54]
 [37 27 41 35 27 79]
 [52 38 68 48 77 64]
 [94 52 26 98 43 20]
 [38 31 42 98 61 84]]
matriz de 3 filas y 10 columnas
 [[ 6 72 66  9  0 54 37 27 41 35]
 [27 79 52 38 68 48 77 64 94 52]
 [26 98 43 20 38 31 42 98 61 84]]
matriz de ? filas y 15 columnas
 [[ 6 72]
 [66  9]
 [ 0 54]
 [37 27]
 [41 35]
 [27 79]
 [52 38]
 [68 48]
 [77 64]
 [94 52]
 [26 98]
 [43 20]
 [38 31]
 [42 98]
 [61 84]]


##resolviendo un problema de álgebra lineal##

Se desea resolver el sistema de ecuaciones lineales:

$6x_1 -3x_2+x_3=11$

$x_1 - 7x_2+x_3=10$

$2x_1 +x_2-8x_3=-15$

A continuación se mostrarán dos técnicas para resolver este sistema

In [0]:
#independientemente de la técnica a resolver se deben crear las matrices A (coeficientes) y b (resultados)
A=np.array([[6,-3, 1],[1, -7, 1],[2, 1, -8]])
resultados = np.array([11, 10,-15])
b=resultados.reshape(3,1) #se transpone la matriz 
print("A:\n",A)
print("b:\n",b)


A:
 [[ 6 -3  1]
 [ 1 -7  1]
 [ 2  1 -8]]
b:
 [[ 11]
 [ 10]
 [-15]]


In [0]:
#primera técnica (aplicar la multiplicación por la inversa)
Ainv = np.linalg.inv(A)
print("A multiplicado por su inversa\n", np.dot(A,Ainv))
print("inversa de A:\n",Ainv)
sol1 = np.dot(Ainv,b)
print("solución técnica 1\n", sol1)

A multiplicado por su inversa
 [[ 1.00000000e+00 -5.55111512e-17  0.00000000e+00]
 [-2.77555756e-17  1.00000000e+00  1.38777878e-17]
 [-5.55111512e-17  0.00000000e+00  1.00000000e+00]]
inversa de A:
 [[ 0.17460317 -0.07301587  0.01269841]
 [ 0.03174603 -0.15873016 -0.01587302]
 [ 0.04761905 -0.03809524 -0.12380952]]
solución técnica 1
 [[ 1.]
 [-1.]
 [ 2.]]


In [0]:
#segunda técnica (resolver directamente en numpy)
sol2 = np.linalg.solve(A,b)
print("solución técnica 2\n", sol2)

solución técnica 2
 [[ 1.]
 [-1.]
 [ 2.]]


In [0]:
print("la solución del sistema de ecuaciones es:")
i=1
for x in sol1:
  print("x_",i,"=", x[0])
  i+=1

la solución del sistema de ecuaciones es:
x_ 1 = 0.9999999999999993
x_ 2 = -1.0
x_ 3 = 2.0
